version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app 
      - /app/node_modules 
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=''
      - DB_NAME=personal_finance_db

  db:
    image: mysql:8.0
    container_name: mysql_fin_ease
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_DATABASE=personal_finance_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: