version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app # Mapeia a pasta backend para o diretório de trabalho do container
      - /app/node_modules # Garante que as dependências persistam
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=sua_senha_mysql # Certifique-se de que a senha está aqui
      - DB_NAME=personal_finance_db

  db:
    image: mysql:8.0
    container_name: mysql_fin_ease
    environment:
      - MYSQL_ROOT_PASSWORD=sua_senha_mysql # E aqui
      - MYSQL_DATABASE=personal_finance_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: